appLabel: configserver

deploymentName: configserver-deployment
serviceName: configserver-ms
appName: configserver-ms

service:
  type: LoadBalancer
  port: 8071
  targetPort: 8071
  loadBalancerIP: 10.10.10.10

replicaCount: 1
image:
  repository: mykhailorudyk/configserver
  tag: latest

containerPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
database_enabled: false
rabbitmq_enabled: true

probe_article_microservice_enabled: false
probe_eureka_and_configserver_enabled: false