global:
  scrape_interval:     10s # Set the scrape interval to every 10 seconds.
  evaluation_interval: 10s # Evaluate rules every 10 seconds.

scrape_configs:
  - job_name: 'articles'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'articles:8091' ]
  - job_name: 'review'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'review:8092' ]
  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'apigateway:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]
  