server:
  port: 8761

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

endpoints:
  shutdown:
    enabled: true