appLabel: review-ms

deploymentName: review-deployment
serviceName: review-ms
appName: review-ms

service:
  type: ClusterIP
  port: 8092
  targetPort: 8092

replicaCount: 1
image:
  repository: mykhailorudyk/review
  tag: latest

containerPort: 8092

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
database_enabled: true
rabbitmq_enabled: true

probe_article_microservice_enabled: false
probe_eureka_and_configserver_enabled: true