appLabel: apigateway

deploymentName: apigateway-deployment
serviceName: apigateway-ms
appName: apigateway-ms

service:
  type: NodePort
  port: 8072
  targetPort: 8072
  nodePort: 30000

replicaCount: 1
image:
  repository: mykhailorudyk/apigateway
  tag: latest

containerPort: 8072

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
database_enabled: false
rabbitmq_enabled: true

probe_article_microservice_enabled: true
probe_eureka_and_configserver_enabled: false