server:
  port: 8071
spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/misharyduk/ArticleInsight-Config.git"
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
    rabbit:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
#        native:
#          search-locations: "classpath:/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


encrypt:
  key: ${ENCRYPTION_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"