apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: mykhailorudyk/eurekaserver:v4
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: articleinsight-configmap
              key: EUREKASERVER_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: articleinsight-configmap
              key: SPRING_CONFIG_IMPORT

---

apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761