services:
  articleinsight-postgres:
    container_name: articleinsight-postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - articleinsight-postgres-data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    networks:
      - articleinsight-network
  
  articleinsight-pgadmin:
    container_name: articleinsight-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - articleinsight-pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - articleinsight-network

volumes:
  articleinsight-postgres-data:
  articleinsight-pgadmin-data:

networks:
  articleinsight-network:
    driver: bridge
